import fs from "node:fs";
import path from "node:path";
import { z } from "zod";
import {
  cityTableSchema,
  corridorTableSchema,
  countryTableSchema,
  deflatorTableSchema,
  fxTableSchema,
  operatorTableSchema,
  programmeTableSchema,
  projectSchema,
} from "../src/lib/schema";

/**
 * Publish the zod schemas as JSON Schema, for editors.
 *
 * A contributor adding a project had to derive the shape by reading
 * src/lib/schema.ts. With these files committed and a "$schema" key in each
 * data file, VS Code and every other JSON-Schema-aware editor gives
 * completion, inline docs and live validation, so a mistake surfaces while
 * typing rather than in CI.
 *
 * `npm run data:schema`
 */

const OUT_DIR = path.join(process.cwd(), "schema");

const TARGETS = [
  { file: "project.schema.json", schema: projectSchema, title: "InfraWorldWide project" },
  { file: "countries.schema.json", schema: countryTableSchema, title: "InfraWorldWide country table" },
  { file: "cities.schema.json", schema: cityTableSchema, title: "InfraWorldWide city table" },
  { file: "deflators.schema.json", schema: deflatorTableSchema, title: "InfraWorldWide deflator table" },
  { file: "fx.schema.json", schema: fxTableSchema, title: "InfraWorldWide FX table" },
  { file: "corridors.schema.json", schema: corridorTableSchema, title: "InfraWorldWide corridor table" },
  { file: "programmes.schema.json", schema: programmeTableSchema, title: "InfraWorldWide funding programme table" },
  { file: "operators.schema.json", schema: operatorTableSchema, title: "InfraWorldWide operator table" },
] as const;

function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  for (const target of TARGETS) {
    // `io: "input"` describes what a hand-written file may contain, which is
    // what an editor validates, rather than the parsed output shape.
    const jsonSchema = z.toJSONSchema(target.schema, {
      io: "input",
      // Refinements such as "an opened lot needs dates.opened" have no JSON
      // Schema equivalent. Keep going and let data:validate enforce them.
      unrepresentable: "any",
    }) as Record<string, unknown>;

    jsonSchema.title = target.title;
    jsonSchema.$comment =
      "Generated by scripts/emit-json-schema.ts. Do not edit by hand; run `npm run data:schema`.";
    // A data file may carry a "$schema" pointer; the schema has to allow it.
    if (jsonSchema.properties && typeof jsonSchema.properties === "object") {
      (jsonSchema.properties as Record<string, unknown>).$schema = {
        type: "string",
        description: "Editor hint. Ignored by the loader.",
      };
    }

    const out = path.join(OUT_DIR, target.file);
    fs.writeFileSync(out, `${JSON.stringify(jsonSchema, null, 2)}\n`);
    console.log(`wrote ${path.relative(process.cwd(), out)}`);
  }
}

main();
